### ISSUE TITLE
DBException$FileLocked while reading balance

### ISSUE THREAD

**Issue by MCUmbrella** [NinekoTheCat/Catconomy#47]
**Describe the bug**
The MapDB storage method locks the database file and makes it inaccessible to other plugins, causing the code that gets the player's money to throw `org.mapdb.DBException$FileLocked`

**To Reproduce**
1. Execute any code related to getting money from the player. For example, wait in the tab or chest menu
2. See error

**Expected behavior**
Any plugin can get the balance normally at any time

**Screenshots**
Not needed

**Server Info (please complete the following information):**
—OS: Linux
— Java: openjdk version "11.0.13" 2021-10-19 LTS
—Version 0.0.10

**CCLogs**
Nothing useful. Just some transactions: https://www.toptal.com/developers/hastebin/gedekukame.css

**Server logs**
https://www.toptal.com/developers/hastebin/likayeyubo.properties
https://www.toptal.com/developers/hastebin/xafuxasune.yaml

**Additional context**
It looks like the `catconomy` command is also unresponsive after that error. I haven't determined further

**Comment by NinekoTheCat** [comment]
I am unable to replicate this bug with the newest version of ChestCommands and the economy commands work just fine. 
Could you send me something so that I can replicate your environment?

**Comment by NinekoTheCat** [comment]
> I am unable to replicate this bug with the newest version of ChestCommands and the economy commands work just fine. Could you send me something so that I can replicate your environment?

Adding to that In the code of CatConomy after each operation is done the DB lock is released

**Comment by MCUmbrella** [comment]
The environment that can reproduce the problem is:
- Server software: mohist 1.16.5 build 910
- Java version: 11
- Plugins:
  - catconomy-0.0.10
  - latest chestcommands
  - luckperms-5.3.1
  - placeholerapi-2.11.1
  - latest plugmanX
  - tab-2.9.2
  - vault-1.7.3<br>

I have prepared a copy of my test environment and you can [download it here](https://cowtransfer.com/s/d111a02f5f7841)

**Comment by NinekoTheCat** [comment]
> The environment that can reproduce the problem is:
> 
>     * Server software: mohist 1.16.5 build 910
> 
>     * Java version: 11
> 
>     * Plugins:
>       
>       * catconomy-0.0.10
>       * latest chestcommands
>       * luckperms-5.3.1
>       * placeholerapi-2.11.1
>       * latest plugmanX
>       * tab-2.9.2
>       * vault-1.7.3
> 
> 
> I have prepared a copy of my test environment and you can [download it here](https://cowtransfer.com/s/d111a02f5f7841)
try this build I just made
https://cowtransfer.com/s/e4638789e48045

**Comment by MCUmbrella** [comment]
Pretty good! Looks like the problem is gone. I tried playing for 10mins and didn't see the any error output. I'm curious how you fix it

**Comment by NinekoTheCat** [comment]
> Pretty good! Looks like the problem is gone. I tried playing for 10mins and didn't see the any error output. I'm curious how you fix it

I just attached the DB object to a companion and had every instance of the default implementation use that.
Obviously checking if it exists before actually making the DB object.

**Comment by MCUmbrella** [comment]
Got it, thank you👍

**Comment by NinekoTheCat** [comment]
> Got it, thank you+1

np. CatConomy 0.0.11 has the fix
