### ISSUE TITLE
'/balance' command shouldn't be executed by console

### ISSUE THREAD

**Issue by MCUmbrella** [NinekoTheCat/Catconomy#48]
**Describe the bug**
The plugin is missing necessary sender type check when performing player-only commands. When the `/bal` command is executed by the console the plugin will throw `ClassCastException`

**To Reproduce**
1. Type `/bal` in the console
2. See error

**Expected behavior**
The plugin denied to perform the command and print an error message (e.g. "This command is player-only")

**Screenshots**
Not needed

**Server Info (please complete the following information):**
—OS: Linux
— Java: openjdk version "11.0.13" 2021-10-19 LTS
—Version 0.0.10

**CCLogs**
Not needed

**Server logs**
https://www.toptal.com/developers/hastebin/ivocusopot.properties

**Additional context**
None

**Comment by NinekoTheCat** [comment]
Thank you for writing about this bug, I will get to fixing it right away.
